import Link from "next/link";
import { PublicNav } from "@/components/marketing/PublicNav";
import { PublicFooter } from "@/components/marketing/PublicFooter";
import { ContextWeb } from "@/components/marketing/ContextWeb";
import { TerminalDemo } from "@/components/marketing/TerminalDemo";
import { Ticker } from "@/components/marketing/Ticker";
import { Container, Eyebrow } from "@/components/ui/Container";
import { LinkButton } from "@/components/ui/Button";
import { commercialScope } from "@/lib/commercial-scope";
import { ArrowUpRight, ArrowDown, Target, Search, Palette, KanbanSquare, Zap, Check, Share2, MessageSquare } from "lucide-react";

const modules = [
  { icon: Target, label: "BUILD", title: "Encontrá tu dirección.", body: "Definí a quién ayudás, qué ofrecés y por qué importa. La base que da sentido a cada acción.", tags: ["Estrategia", "ICP", "Oferta"], href: "/build/estrategia", action: "Explorar estrategia" },
  { icon: Search, label: "DISCOVER", title: "Conectá con quien importa.", body: "Empresas, personas y señales relevantes para construir relaciones con contexto, desde el inicio.", tags: ["Empresas", "Contactos", "Señales"], href: "/prospeccion", action: "Explorar descubrimiento" },
  { icon: Palette, label: "STUDIO & SOCIAL", title: "Hacé que tu voz llegue.", body: "Una misma estrategia para tus contenidos, piezas creativas y conversaciones en LinkedIn.", tags: ["Studio", "LinkedIn", "Calendario"], href: "/social/linkedin", action: "Explorar contenido" },
  { icon: KanbanSquare, label: "SELL & MANAGE", title: "Dale continuidad a cada oportunidad.", body: "Campañas, tareas y pipeline conectados para que el siguiente paso tenga toda la información.", tags: ["Oportunidades", "Actividad", "CRM"], href: "/crm", action: "Explorar ventas" },
];
const steps = [
  ["Definí la base", "Tu negocio, tu cliente ideal y tu propuesta de valor se convierten en el contexto común."],
  ["Activá las conexiones", "Relacioná investigación, contenidos y campañas con las empresas a las que querés llegar."],
  ["Aprendé y evolucioná", "Conectá actividad y oportunidades para entender qué funciona y orientar tu próximo paso."],
];
const faqs = [
  ["¿Qué es Capsule GTM?", "Es un espacio de trabajo B2B para construir tu estrategia, organizar el CRM, preparar contenido y acompañar el proceso comercial. Está pensado para equipos de marketing, inteligencia artificial y tecnología."],
  ["¿Capsule ejecuta la venta por mi equipo?", "Tu equipo mantiene la ejecución comercial. Capsule reúne la estrategia, los procesos y los materiales para que puedan implementarlos internamente."],
  ["¿Puedo crear contenido y diseños para LinkedIn?", "Studio incluye creación de posts, briefs, calendario editorial y generación de imágenes. La publicación directa requiere una aplicación de LinkedIn con permisos aprobados y una cuenta autorizada."],
  ["¿Está conectado todo automáticamente?", "Las conexiones requieren configuración y permisos. Cada módulo distingue la configuración de servidor de una cuenta conectada. No se simulan publicaciones, mensajes ni contactos."],
];
export default function Home() {
  return <><PublicNav/><main id="contenido">
    <Container className="capsule-hero grid items-center gap-12 lg:grid-cols-[1.12fr_1fr]">
      <div><Eyebrow className="!text-muted !text-[10px]">El punto de encuentro de tu go-to-market</Eyebrow>
        <h1 className="mt-7">Grandes ideas.<br/>Mejores conexiones.<br/><span className="text-lime">Más posibilidades.</span></h1>
        <p className="mt-7 max-w-lg text-[17px] leading-[1.8] text-muted">Tu estrategia, tus datos y tus conversaciones, en la misma dirección. Una nueva forma de conectar marketing y ventas B2B.</p>
        <div className="mt-8 flex flex-wrap items-center gap-7"><LinkButton href="/dashboard" size="lg">Descubrí tu Capsule <ArrowUpRight className="ml-3 h-5 w-5"/></LinkButton><a href="#proceso" className="flex items-center gap-3 text-sm hover:text-lime">Así se conecta todo <ArrowDown className="h-4 w-4"/></a></div>
        <p className="mt-6 text-xs text-muted-2">Para empresas de marketing, inteligencia artificial y tecnología.</p>
      </div><ContextWeb/>
    </Container>
    <Container className="pb-8"><TerminalDemo/></Container>
    <Container><Ticker/></Container>
    <section id="sistema" className="capsule-section"><Container>
      <div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><Eyebrow className="!text-muted">Menos fragmentación. Más contexto.</Eyebrow><h2 className="capsule-heading mt-5">Todo parte de una idea.<br/>Todo vive en <span className="text-lime">tu Capsule.</span></h2></div><p className="max-w-sm text-muted">Del primer insight a la próxima conversación comercial. Cada área aporta contexto a la siguiente.</p></div>
      <div className="mt-10 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{modules.map(({icon:Icon,...m},i)=><article key={m.label} className={"flex flex-col rounded-3xl border p-6 "+(i===0?"border-lime bg-lime text-lime-foreground":"border-surface-border bg-surface/80 backdrop-blur-xl")}>
        <div className="flex items-center gap-3 text-[10px] tracking-widest"><Icon className={"h-7 w-7 "+(i===0?"":"text-lime")} strokeWidth={1.5}/>{m.label}</div><h3 className="mt-7 text-[25px] font-medium leading-tight tracking-tight">{m.title}</h3><p className={"mt-4 text-sm leading-relaxed "+(i===0?"text-[#48513b]":"text-muted")}>{m.body}</p><div className="mb-7 mt-auto flex flex-wrap gap-1.5 pt-6">{m.tags.map(t=><span key={t} className={"rounded-full border px-2.5 py-1 text-[10px] "+(i===0?"border-[#a8c779]":"border-[#626758]")}>{t}</span>)}</div><Link href={m.href} className="flex items-center justify-between gap-2 border-t border-current/20 pt-4 text-xs hover:underline">{m.action}<ArrowUpRight className="h-4 w-4"/></Link>
      </article>)}</div>
    </Container></section>
    <section id="plataforma" className="capsule-section"><Container><Eyebrow className="!text-muted">Tu espacio de trabajo</Eyebrow><h2 className="capsule-heading mt-5">De la estrategia<br/><span className="text-lime">al trabajo de todos los días.</span></h2>
      <div className="mt-10 grid gap-5 md:grid-cols-3">{[
        {icon:KanbanSquare,title:"CRM",body:"Empresas, contactos, oportunidades y actividad. Seguí cada relación desde la primera conversación.",href:"/crm",label:"Abrir CRM"},
        {icon:Share2,title:"LinkedIn & Studio",body:"Prepará posts y diseños, organizá tus borradores y revisá el estado de conexión de LinkedIn.",href:"/social/linkedin",label:"Abrir LinkedIn"},
        {icon:MessageSquare,title:"Asistente GTM",body:"Trabajá ideas, mensajes y decisiones comerciales con el asistente de marketing y ventas.",href:"/chat",label:"Abrir asistente"},
      ].map(({icon:Icon,...m})=><article key={m.title} className="flex flex-col rounded-3xl border border-surface-border bg-surface/70 p-7"><Icon className="h-7 w-7 text-lime" strokeWidth={1.5}/><h3 className="mt-5 text-2xl">{m.title}</h3><p className="mb-7 mt-3 text-sm leading-relaxed text-muted">{m.body}</p><LinkButton href={m.href} variant="outline" className="mt-auto w-fit">{m.label}<ArrowUpRight className="h-4 w-4"/></LinkButton></article>)}</div>
    </Container></section>
    <section id="incluye" className="capsule-section"><Container><Eyebrow className="!text-muted">El sistema comercial completo</Eyebrow><h2 className="capsule-heading mt-5">Doce frentes de trabajo.<br/><span className="text-lime">Una misma dirección.</span></h2><p className="mt-5 max-w-2xl text-muted">Estrategia, procesos y materiales para implementar con tu equipo. Abrí cada área para conocer su alcance y trabajar en ella.</p>
      <div className="mt-9 grid items-start gap-4 md:grid-cols-2 xl:grid-cols-3">{commercialScope.map(a=><details key={a.title} className="group rounded-3xl border border-surface-border bg-surface/65 p-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 font-display text-base font-medium">{a.title}<span className="text-xl text-lime group-open:rotate-45">+</span></summary><p className="mt-4 text-sm leading-relaxed text-muted">{a.description}</p><p className="mt-3 text-sm"><span className="text-lime">Entregable:</span> {a.deliverable}</p><Link href={a.href} className="mt-5 inline-flex items-center gap-2 text-sm text-lime hover:underline">Abrir área <ArrowUpRight className="h-4 w-4"/></Link></details>)}</div>
    </Container></section>
    <section id="proceso" className="capsule-section"><Container><Eyebrow className="!text-muted">Del contexto a la acción</Eyebrow><h2 className="capsule-heading mt-5">Crecer es conectar<br/><span className="text-lime">los siguientes pasos.</span></h2><div className="mt-10 grid gap-10 md:grid-cols-3">{steps.map(([title,body],i)=><article key={title} className="border-t border-[#727a61] pt-6"><span className="flex h-10 w-10 items-center justify-center rounded-full border border-[#626a50] text-xs text-lime">0{i+1}</span><h3 className="mt-6 text-2xl font-medium tracking-tight">{title}</h3><p className="mt-3 text-sm leading-relaxed text-muted">{body}</p></article>)}</div><div className="mt-10 flex flex-wrap items-center gap-3 rounded-3xl border border-surface-border bg-surface/50 p-6 text-sm">{["Primer contacto","Interés","Reunión","Propuesta","Primer cliente"].map((s,i)=><span key={s} className="flex items-center gap-3">{i>0&&<ArrowUpRight className="h-4 w-4 text-lime"/>}{s}</span>)}<Link href="/crm/pipeline" className="ml-auto text-lime hover:underline">Ver pipeline ↗</Link></div></Container></section>
    <section className="capsule-section"><Container><div className="grid gap-10 rounded-[30px] border border-[#4f5b3e] bg-[#30362a]/90 p-7 md:grid-cols-[1.2fr_1fr] md:p-12"><div><Eyebrow className="!text-muted">IA con contexto. Decisiones humanas.</Eyebrow><h2 className="capsule-heading mt-5">Tu inteligencia comercial,<br/><span className="text-lime">con una visión compartida.</span></h2><p className="mt-6 text-sm leading-relaxed text-muted">Conectá lo que sabés de tu negocio con lo que aprendés de tu mercado. Tu equipo revisa los materiales y mantiene el control de cada acción comercial.</p><div className="mt-6 space-y-3">{["Evidencia antes que suposiciones","Borradores antes de ejecutar","Tu equipo conserva el control"].map(t=><p key={t} className="flex gap-3 text-sm"><Check className="h-4 w-4 text-lime"/>{t}</p>)}</div></div><div className="flex flex-col justify-center gap-3">{[["CONTEXTO DE NEGOCIO","Tu marca. Tu oferta. Tu cliente ideal."],["CONTEXTO COMERCIAL","Señales. Conversaciones. Oportunidades."],["UNA MEJOR PRÓXIMA ACCIÓN","Relevante para tu negocio. Revisada por tu equipo."]].map(([tag,t],i)=><div key={tag} className={"rounded-2xl border p-5 "+(i===2?"border-lime bg-lime text-lime-foreground":"border-[#58664a] bg-[#394132]")}><span className="text-[10px] tracking-wider opacity-75">{tag}</span><p className="mt-2 text-sm">{t}</p></div>)}</div></div></Container></section>
    <section id="precios" className="capsule-section"><Container><Eyebrow className="!text-muted">Dos motores, una estrategia</Eyebrow><h2 className="capsule-heading mt-5">Outbound e Inbound.<br/><span className="text-lime">El mismo contexto.</span></h2><div className="mt-8 grid gap-5 md:grid-cols-3">{[["Outbound","Prospección, priorización de cuentas y seguimiento comercial."],["Inbound","Contenido, LinkedIn y materiales para generar demanda."],["Sistema completo","Estrategia, CRM, Studio y ambos canales de adquisición."]].map(([t,d])=><article key={t} className="rounded-3xl border border-surface-border bg-surface/70 p-7"><h3 className="text-xl">{t}</h3><p className="mt-3 text-sm text-muted">{d}</p><p className="mt-6 text-sm text-lime">Tarifas por definir</p><p className="mt-1 text-xs text-muted">No hay precios publicados ni cobros habilitados.</p></article>)}</div></Container></section>
    <section className="capsule-section pb-20"><Container className="grid gap-8 md:grid-cols-2"><div><Eyebrow className="!text-muted">Un poco más de contexto</Eyebrow><h2 className="capsule-heading mt-5">Buenas preguntas.<br/><span className="text-lime">Respuestas claras.</span></h2></div><div>{faqs.map(([q,a])=><details key={q} className="group border-b border-surface-border py-5"><summary className="flex cursor-pointer list-none justify-between gap-5">{q}<span className="text-xl text-lime group-open:rotate-45">+</span></summary><p className="mt-4 text-sm leading-relaxed text-muted">{a}</p></details>)}</div></Container></section>
    <Container className="pb-16"><div className="capsule-closing p-8 sm:p-14"><Zap className="closing-bolt" fill="currentColor" strokeWidth={0} aria-hidden="true"/><div className="relative"><Eyebrow className="!text-[#586747]">El siguiente paso empieza con una visión</Eyebrow><h2 className="my-7">Todo tu GTM.<br/>En una <span className="text-[#657e43]">Capsule.</span></h2><LinkButton href="/dashboard" size="lg" className="border-0" style={{ background: "#252b1e", color: "#d9f99b" }}>Explorá las posibilidades <ArrowUpRight className="ml-4 h-5 w-5"/></LinkButton></div></div></Container>
  </main><PublicFooter/></>;
}
