"use client";
import { useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/Button";
import { TemperatureBadge } from "@/components/crm/TemperatureBadge";
import type { Temperature } from "@/lib/qualification-rules";
export type ScorableContact = { id:string; full_name:string; role_title:string|null; temperature:Temperature|null; company_name:string|null };
type Analysis = {contactId:string;score_total:number|null;reason:string;accion:string};
export function LeadScoringTool({contacts,connected,initialContactId}:{contacts:ScorableContact[];connected:boolean;initialContactId?:string}){
 const [selected,setSelected]=useState<string[]>(initialContactId?[initialContactId]:[]);const [results,setResults]=useState<Analysis[]>([]);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState("");
 async function analyze(){setBusy(true);setNotice("");try{const r=await fetch("/api/ai/scoring-leads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contactIds:selected})});const d=await r.json();if(!r.ok)throw new Error(d.message??"No se pudo analizar.");setResults(d.leads);}catch(e){setNotice(e instanceof Error?e.message:"No se pudo analizar.");}finally{setBusy(false);}}
 return <div className="space-y-4 p-5 sm:p-8"><p className="glass-panel rounded-2xl p-4 text-sm text-muted">El semáforo se actualiza automáticamente con interacciones registradas. Este análisis opcional evalúa el encaje con tu estrategia confirmada; una recomendación de IA no prueba interés ni cambia el semáforo.</p>
 {!connected||!contacts.length?<Link href="/prospeccion" className="text-sm text-brand">Buscá y guardá contactos reales para analizarlos →</Link>:<><div className="glass-panel divide-y divide-surface-border overflow-hidden rounded-2xl">{contacts.map(c=>{const result=results.find(r=>r.contactId===c.id);return <article key={c.id} className="p-4"><div className="flex flex-wrap items-center justify-between gap-3"><label className="flex items-center gap-3 text-sm"><input type="checkbox" disabled={busy} checked={selected.includes(c.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,c.id]:v.filter(id=>id!==c.id))}/><span><span className="block font-medium">{c.full_name}</span><span className="text-xs text-muted">{c.company_name??"Sin empresa"} · {c.role_title??"Sin cargo"}</span></span></label><TemperatureBadge value={c.temperature}/></div>{result&&<div className="mt-3 rounded-xl bg-surface-2 p-3 text-sm"><p className="font-medium">{result.score_total==null?"Datos insuficientes para puntuar":"Encaje sugerido: "+result.score_total+"/100"}</p><p className="mt-1 text-xs text-muted">{result.reason}</p><p className="mt-2 text-xs">{result.accion}</p><Link href={"/crm/contactos/"+c.id} className="mt-2 inline-block text-xs text-brand">Ver señales e historial →</Link></div>}</article>;})}</div><Button disabled={busy||!selected.length||selected.length>50} onClick={analyze}>{busy?"Analizando…":"Analizar "+selected.length+" contactos"}</Button><p className="text-xs text-muted">Hasta 50 por análisis. Se usa el ICP confirmado en Estrategia.</p></>}
 {notice&&<p role="alert" className="text-sm text-danger">{notice}</p>}</div>;
}
